import { Prop, Schema, SchemaFactory } from "@nestjs/mongoose";
import { HydratedDocument, Types } from "mongoose";

export type MessageDocument = HydratedDocument<MessageEntity>;

export type MessageFileType =
  | "photo"
  | "sticker"
  | "video"
  | "audio"
  | "voice"
  | "document";

@Schema({ timestamps: true })
export class MessageEntity {
  public static COLLECTION_NAME = "message";

  @Prop({ required: true, index: true })
  chatId: number;

  @Prop({ required: true, index: true })
  messageId: number;

  @Prop()
  replyToMessageId?: number;

  @Prop({ required: true, index: true })
  userId: number;

  @Prop({ required: true })
  text: string;

  /**
   * Indicates whether the message is a technical message
   * such as join/leave notifications, chat changes, etc.
   */
  @Prop()
  technicalMessage?: boolean;

  @Prop()
  fileDescription?: string;

  @Prop()
  fileType?: MessageFileType;

  @Prop()
  fileUniqueId?: string;

  @Prop({ default: Date.now })
  date: Date;

  @Prop()
  forwardedFromUserId?: number;

  @Prop({ default: null })
  conversationIds: Array<number> | null;

  /**
   * Indicates whether the message was generated by the generative AI
   * service (some bot messages may appear as user messages if they are
   * sent on behalf of the user – i.e. translations)
   * Marking only this like model should avoid LLM strokes of confusion.
   * Probably.
   *
   * @todo: [LOW] Evaluate if it got better with time.
   */
  @Prop()
  isGenerated?: boolean;

  // No need for prop its managed by timestamps: true
  updatedAt?: Date;
  createdAt?: Date;
}

export const MessageSchema = SchemaFactory.createForClass(MessageEntity);
// Expire messages after 30 days
MessageSchema.index({ createdAt: 1 }, { expireAfterSeconds: 2592000 });
