name: Deploy (Hetzner)

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

concurrency:
  group: production-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare env file
        run: echo "$PRODUCTION_ENV" > .env
        env:
          PRODUCTION_ENV: ${{ secrets.PRODUCTION_ENV }}

      - name: Write GCP key (not baked into image)
        run: echo "$GCP_KEY" > gcp-key.json
        env:
          GCP_KEY: ${{ secrets.GCP_KEY }}

      - name: Determine version tag
        id: meta
        run: |
          if [ -n "${GITHUB_REF_NAME}" ]; then
            BASE_TAG=${GITHUB_REF_NAME}
          else
            BASE_TAG=${GITHUB_SHA::7}
          fi
          echo "tag=$BASE_TAG" >> "$GITHUB_OUTPUT"

      - name: Build images with docker-compose
        run: |
          docker compose build

      - name: Recreate services
        run: |
          docker compose down --remove-orphans
          docker compose up -d --remove-orphans

      - name: Show status
        run: docker compose ps

      - name: Tail recent logs
        run: docker compose logs --since=5m app | tail -n 200 || true

      - name: Prune dangling images
        run: docker image prune -f || true
